<?php

namespace Database\Seeders;

use App\Models\indicador_criterio;
use Illuminate\Database\Seeder;

use function Ramsey\Uuid\v1;

class indicador_criterios extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $criterios=[
            [
                'indicador_id'=>1,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>1,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>2,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>3,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>4,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>4,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>5,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>5,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>6,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>6,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>7,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>7,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>8,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>9,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>10,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>11,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>12,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>13,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>13,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>14,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>15,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>16,
                'criterio_id'=>1
            ],

            [
                'indicador_id'=>17,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>18,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>18,
                'criterio_id'=>2
                //id 26 en tabla indicador_criterio
            ],
            [
                'indicador_id'=>19,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>20,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>21,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>22,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>23,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>24,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>25,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>26,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>26,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>27,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>28,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>29,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>30,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>31,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>32,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>33,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>34,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>35,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>36,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>37,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>38,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>38,
                'criterio_id'=>4
            ],
            [
                'indicador_id'=>39,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>40,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>40,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>39,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>41,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>43,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>42,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>44,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>45,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>46,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>47,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>48,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>49,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>50,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>50,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>51,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>52,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>53,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>54,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>55,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>56,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>57,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>58,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>60,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>61,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>62,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>63,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>64,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>65,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>66,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>67,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>68,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>69,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>70,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>70,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>71,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>72,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>73,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>74,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>75,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>76,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>77,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>78,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>78,
                'criterio_id'=>4
            ],
            [
                'indicador_id'=>79,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>79,
                'criterio_id'=>4
            ],
            [
                'indicador_id'=>80,
                'criterio_id'=>2
            ],
            [
                'indicador_id'=>81,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>82,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>82,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>83,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>84,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>85,
                'criterio_id'=>4
            ],
            [
                'indicador_id'=>86,
                'criterio_id'=>3
            ],
            [
                'indicador_id'=>86,
                'criterio_id'=>4
            ],
            [
                'indicador_id'=>87,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>88,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>89,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>90,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>90,
                'criterio_id'=>4
            ],
            [
                'indicador_id'=>91,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>92,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>93,
                'criterio_id'=>1
            ],
            [
                'indicador_id'=>59,
                'criterio_id'=>1
            ]
            
        ];

        foreach ($criterios as $criterio) {
            indicador_criterio::create([
                'indicador_id'=>$criterio['indicador_id'],
                'criterio_id'=>$criterio['criterio_id']
            ]);
        }
    }
}
